name: Salim Khouri
favicon: null
layout_spectrum: 0
typography_spectrum: 0.1401868173852563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#484848'
    - '#999999'
    - '#696969'
    - '#b2b2b2'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.8578642199281603
purpose: []
